### ISSUE TITLE
Auto lipsync with mp3 file *Feature Request*

### ISSUE THREAD

**Issue by UncleBob2** [met4citizen/TalkingHead#10]
Hi there,

Is there a way to feed in the mp3 file directly and to have the lip sync to the mp3 file? 

<!DOCTYPE html>
<html>
<head>
  <title>Talking Head - MP3 example</title>
  <style>
    body, html { width:100%; height:100%; max-width: 800px; margin: auto; position: relative; background-color: black; color: white; }
    #avatar { display: block; width:100%; height:100%; }
    #controls { display: block; position: absolute; top: 10px; left: 10px; right: 10px; height: 50px; }
    #text { position: absolute; width: Calc( 100% - 110px ); height: 100%; top: 0; left: 0; bottom: 0; right: 110px; font-family: Arial; font-size: 20px; visibility: hidden; } /* Hide the text input as it's not needed for MP3 playback */
    #speak { display: block; position: absolute; top: 0; bottom: 0; right: 0; height: 100%; width: 100px; font-family: Arial; font-size: 20px; }
  </style>
  <script type="importmap">
  {
    "imports": {
      "three": "https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js/+esm",
      "three/examples/": "https://cdn.jsdelivr.net/npm/three@0.161.0/examples/",
      "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.161.0/examples/jsm/",
      "dompurify": "https://cdn.jsdelivr.net/npm/dompurify@3.0.6/+esm",
      "marked": "https://cdn.jsdelivr.net/npm/marked@11.2.0/+esm",
      "talkinghead": "https://cdn.jsdelivr.net/gh/met4citizen/TalkingHead@1.0.0/modules/talkinghead.mjs"
    }
  }
  </script>
  <script type="module">
    import { TalkingHead } from "talkinghead";

    let head;
    let audio = new Audio('taviet.mp3'); // URL to your MP3 file

    document.addEventListener('DOMContentLoaded', async function(e) {
      const nodeAvatar = document.getElementById('avatar');
      head = new TalkingHead(nodeAvatar, {
        ttsEndpoint: "https://dummy.endpoint/tts", // Placeholder endpoint
        ttsApikey: "dummy-api-key", // Placeholder API key
        cameraView: "upper"
      });

      try {
        await head.showAvatar({
          url: 'https://models.readyplayer.me/64bfa15f0e72c63d7c3934a6.glb?morphTargets=ARKit,Oculus+Visemes,mouthOpen,mouthSmile,eyesClosed,eyesLookUp,eyesLookDown&textureSizeLimit=1024&textureFormat=png',
          body: 'F',
          avatarMood: 'neutral',
        });
      } catch (error) {
        console.log(error);
      }

      const nodeSpeak = document.getElementById('speak');
      nodeSpeak.addEventListener('click', function () {
        audio.play();
      });

    });
  </script>
</head>
<body>
  <div id="avatar"></div>
  <div id="controls">
    <input id="text" type="text" value="Hi there. How are you? I'm fine." style="visibility: hidden;"> 
    <input id="speak" type="button" value="Play MP3">
  </div>
</body>
</html>

**Comment by met4citizen** [comment]
There is already a way to achieve this using the `speakAudio` method. However, it's not entirely automatic. Alongside the audio, you also need to supply the words and timestamps for lip-sync and subtitles. Here is a simple example:

```javascript
// Speak when clicked
const nodeSpeak = document.getElementById('speak');
nodeSpeak.addEventListener('click', async function () {
  try {
    let response = await fetch("greeting.mp3");
    let arraybuffer = await response.arrayBuffer();
    let audiobuffer = await head.audioCtx.decodeAudioData(arraybuffer);
    let audio = {
      audio: audiobuffer,
      words: ["How","are","you?"],
      wtimes: [100,275,340],
      wdurations: [100,70,100]
    };
    head.speakAudio( audio );
  } catch (error) {
    console.log(error);
  }
});
```
If you need to automatically recognize the words in your MP3 file, you should look for speech recognition services that can return word timestamps. I haven't tried it myself, but for example, OpenAI's Whisper seems to be able to do this:

https://platform.openai.com/docs/guides/speech-to-text/timestamps

It would be, of course, rather nice if the TalkingHead class could automatically recognize words and timestamps. On the other hand, implementing one's own speech recognition service is out of the question, and not fixing the external service allows the calling app to decide which service/approach to use.

**Comment by UncleBob2** [comment]
Thanks for your comment. Greatly appreciated.

**Comment by met4citizen** [comment]
Thank you for bringing this use case to my attention. The `speakAudio` method was originally added to stream PCM audio chunks from external TTS services, and before this, I had not really considered its use beyond that. If at some point you pursue this approach further in your own app, I'm interested in hearing about the results.

It seems, however, that making this feature automatic would require a paid external service for speech-to-text, so at least for now, I'm going to leave that choice to the calling app and close this issue. That said, I think this approach is really interesting and enables some unique use cases. I will surely keep this issue in mind and maybe at some point make a more comprehensive code example using Whisper (or some other speech-to-text service) for reference.

**Comment by Mortezanavidi** [comment]
hello there, i tried to use this example but i'm facing something weird, i created a program which gives me the exact wtimes and wdurations of a mp3 based on the
`
  * @property {string[]} words Words
  * @property {number[]} wtimes Starting times of words
`
but same words, using google api gives me perfect lip sync but with mp3, the lip sync is giberish, again, i checked start and end of my audio in ms, with wavepad i made sure each word have the exact starting points and ~durations, so i know my mp3 wtimes and wdurations are fairly correct, but the lip sync is not even close to the google api one at all

**Comment by met4citizen** [comment]
Interesting. I wouldn't be surprised if the word-level lip-sync accuracy of natural speech recording is not as good as it is with the very consistent Google TTS voices, but if it's not even close, it suggests a bug. 

The problem could well be in the `speakAudio` method. On the other hand, the existing ElevenLabs TTS integration uses the same `speakAudio` method with words, wtimes, and wdurations, and I have not yet encountered or heard of any problems with it. The main difference here is that instead of an array of PCM audio chunks, the audio property now contains an `AudioBuffer`.

I will look into this, but first, I need to make my own test app, and it will take some time.

I don't know if it's possible to add MP3 attachments to these issues, but any additional information you can provide about the problem would be helpful and appreciated. I'm also interested in the approach you are using to extract word timestamps from MP3 files.

**Comment by met4citizen** [comment]
I just made my first attempt at generating a lip-sync sequence from a MP3 file automatically. I didn't encounter any problems, and the lip-sync quality was much better than I expected. Here is a short video clip that I recorded: https://youtu.be/RVSY2TGDH2E

The example code still needs a lot more testing, so I haven't published it yet, but at some point it will be part of the `index.html` test app. However, if you are interested, here are the basic steps that I used:

First, I sent my input MP3 file to OpenAI's Whisper Transcriptions API (I used my existing OpenAI proxy):

```javascript
const form = new FormData();
form.append("file", file);
form.append("model", "whisper-1");
form.append("response_format", "verbose_json" );
form.append("timestamp_granularities[]", "word" );
form.append("timestamp_granularities[]", "segment" );
const response = await fetch( openaiAudioTranscriptionsProxy , {
  method: "POST",
  body: form,
  headers: {
    "Authorization": "Bearer " + await jwtGet()
  }
});
```
The process was fast and the JSON response I got from Whisper looked like this:

![mp3json](https://github.com/met4citizen/TalkingHead/assets/76654952/303f3263-2dd8-4692-ab32-32f435ebd133)

Finally, I just created a new audio object for `speakAudio` by converting seconds to milliseconds:

```javascript
whisperAudio = { audio: audiobuffer, words: [], wtimes: [], wdurations: [] };
json.words.forEach( x => {
  whisperAudio.words.push( x.word );
  whisperAudio.wtimes.push( 1000 * x.start - 150 );
  whisperAudio.wdurations.push( 1000 * (x.end - x.start)  );
});
```
My test MP3 file was short and rather simple, but I have already tested more challenging examples including entire songs. Whisper seems to be good at extracting lyrics and the lip-sync is pretty good, but as expected, singing long notes doesn't look very natural, because the lip-sync works at word-level.

As a side note, the `speakAudio` can already operate at phoneme/viseme level by accepting visemes, vtimes and vdurations, and I know there are some python tools that can extract phonemes and phoneme timestamps from audio files. So, if singing is required, that could be the way to go.
