### ISSUE TITLE
cuts in text when sending to tts

### ISSUE THREAD

**Issue by chang998** [met4citizen/TalkingHead#30]
hello again!
i just wanted to edit something in the code bec it was taking a lot of time generating the voice many times in one text

now lets look at the server logs to understand everything first: (i tried to make it short as possible)

 * Serving Flask app 'apimain'
127.0.0.1 - - [18/Apr/2024 01:24:44] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:24:44] "OPTIONS /moderation_ai HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:24:44] "POST /moderation_ai HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:24:44] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:24:44] "OPTIONS /chatbot HTTP/1.1" 200 -
Received request data:
Last message: {'role': 'user', 'content': 'ask 2 questions about streaming'}
Content of last message: ask 2 questions about streaming
finding response...
2b: Do you have a favorite streamer you watch regularly? And what type of content do you find most entertaining on streams? Let's chat about your streaming preferences. <-------- look here this is the response (1) !
127.0.0.1 - - [18/Apr/2024 01:25:00] "POST /chatbot HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:25:00] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:25:00] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:25:00] "OPTIONS /gtts HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:25:00] "OPTIONS /moderation_ai HTTP/1.1" 200 -
twob Do you have a favorite streamer you watch regularly? <--------- here this is what it sends to the tts server (2) !
127.0.0.1 - - [18/Apr/2024 01:25:00] "POST /moderation_ai HTTP/1.1" 200 -
Sending initial message: {'fn_index': 1, 'session_hash': 'c1p8pn414f'}
Received message: {"msg":"process_starts"}
Received message: {"msg":"process_completed","output"
Audio files in response:
(audio file)
Downloading audio: (audio file)
Audio downloaded successfully.
Generating lip sync data for "C:\Users\kille\Desktop\ai-chatbot\voice.wav".
Progress: [####################] 100%  
Done.
127.0.0.1 - - [18/Apr/2024 01:25:21] "POST /gtts HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:25:25] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:25:25] "OPTIONS /gtts HTTP/1.1" 200 -
And what type of content do you find most entertaining on streams? <---------- another text (3) !
Sending initial message: {'fn_index': 1, 'session_hash': 'c1p8pn414f'}
Received message: {"msg":"process_starts"}
Received message: {"msg":"process_completed","output"
Audio files in response:
(audio file)wav
Audio downloaded successfully.
Generating lip sync data for "C:\Users\kille\Desktop\ai-chatbot\voice.wav". 
Done.
127.0.0.1 - - [18/Apr/2024 01:25:47] "POST /gtts HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:25:51] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 01:25:51] "OPTIONS /gtts HTTP/1.1" 200 -
Let's chat about your streaming preferences. <---------- another text (4) !
Sending initial message: {'fn_index': 1, 'session_hash': 'c1p8pn414f'}
Received message: {"msg":"process_starts"}
Received message: {"msg":"process_completed","output":{"data":
Audio files in response:
(file here)
Downloading audio: (file here)
Audio downloaded successfully.
Progress:
Done.
127.0.0.1 - - [18/Apr/2024 01:26:00] "POST /gtts HTTP/1.1" 200 -

_________________________________________________________________________________________________________________________
i edited //speak in index.html like this:
// Speak
                if ( tts ) {
                  let idx = Math.max(tts.lastIndexOf('\n'));
                  if ( idx !== -1 ) {
                    let s = tts.substring(0, idx + 1);
                    if ( s && s.length ) {
                      tts = tts.substring(idx + 1).trimStart();
                      if ( cfg('voice-type') === 'eleven' ) {
                        await elevenSpeak( s + " ", node );
                      } else if ( cfg('voice-type') === 'microsoft' ) {
                        await microsoftSpeak( s + " ", node );
                      } else {
                        exclude = excludesProcess(s,exclude);
                        await head.speakText( s, {
                          lipsyncLang: cfg('voice-lipsync-lang'),
                          ttsVoice: cfg('voice-google-id'),
                          ttsRate: cfg('voice-google-rate'),
                          ttsPitch: cfg('voice-google-pitch')
                        }, addText.bind(null,node), exclude.excludes );
                      }
                    }
                  }
                }
              }
_________________________________________________________________________________________________________________________________________
removed the lastindexof things but still and i also tried in the gemini part but also still can i get you help (sorry if you found typos or leaked things but i really want to sleep)

**Comment by met4citizen** [comment]
Yes, you are right. Both the TalkingHead class and the test app (index.html) split the text into sentences intentionally, and it is not a bug.

Here are some of the reasons why the text is being sent to TTS in sentences (not a comprehensive list):

- **Streaming text**: When using the class with LLMs, the text output is usually streamed word-by-word. Most TTS engines, Google TTS included, don't support streaming input, so a sentence is a logical unit to wait for before sending the next chunk of text to TTS.
- **TTS input limits**: Different TTS APIs have different limits for maximum input size. For Google TTS, it is 5000 bytes. Note that for certain languages, one character can be several bytes. Moreover, SSML tags, especially the <mark> tags needed for word timestamps, consume a lot of bytes, so the maximum size for text is often less than 2000 bytes. This isn't sufficient for a long paragraph, so breaking at the sentence boundary is safer. (Note: Mark tags are included when counting the max input size, but they are not billed.)
- **Audible breaks**: Breaking the speech in mid-sentence doesn't sound natural, and you can often hear an audible click or an unnatural pause at the break point.
- **Latency**: Instead of waiting for the input text and/or the TTS conversion of a large chunk of text, we can improve latency by sending smaller chunks of text. In fact, the ElevenLabs WebSocket API recommends sending the input word-by-word. However, for ElevenLabs, this can lead to breaks in the audio between words, which sounds unnatural. The best option seems to be to send the text sentence-by-sentence.
- **Facial expressions and movement**: Splitting the text into sentences makes it easier to animate the avatar in a way that reflects the natural flow of speech. For example, making eye contact often looks more natural at the start of a sentence.
- **Billing issues**: If the user interrupts the speech of a long text, we can save TTS characters by not having sent the entire text beforehand. TTS vendors typically bill by characters, not by the number of requests.

**Comment by chang998** [comment]
Thanks for clarifying

Ok but on my side it takes a really long time to do that because Im using a model hosted on hugging face so it waits in cache until it generates the audio.

It won't take much time if you make one long sentence but it will take time when you give it multiple sentences because it will have to wait over and over.

I deleted the cache logs from the logs because  its long but If you want it I can paste it

I'm not saying it's a bug I'm requesting a feature or a way by editing the code to disable it

**Comment by met4citizen** [comment]
OK, I understand. Thank you for elaborating.

To do this in your setup, you should prevent the method `speakText` in `./modules/talkinghead.mjs` from dividing the text into sentences. You can do that by modifying the following Regex rule:

```javascript
const dividersSentence = /[!\.\?\n\p{Extended_Pictographic}]/ug;
```

You can, for example, break the text only if/when it encounters an emoji:

```javascript
const dividersSentence = /[\p{Extended_Pictographic}]/ug;
```

Note: This modification is a hack and I haven't tested it. Furthermore, I will not be making this change/feature to the code for the reasons already mentioned: This is not an issue with Google TTS, this change would increase the latency of starting to speak in typical use cases, it presents a risk that longer texts will encounter TTS errors, avatar's facial expressions and hand movements are no longer synchronized with the sentences, and there can be unwanted billing issues with longer texts.

**Comment by chang998** [comment]
I edited `./modules/talkinghead.mjs` in line 1891 
` const dividersSentence = /[\n{Extended_Pictographic}]/ug; `
but the script still divide the text for some reason
so is there any other way i could try?

thanks for helping me btw

**Comment by chang998** [comment]
well it is working but in the new version the old version isn't 
but anyway thanks for helping me it now generates fast
you really helped me a lot in this project thanks again.
