### ISSUE TITLE
easy-speech

### ISSUE THREAD

**Issue by andre-dietrich** [met4citizen/TalkingHead#52]
Fascinating project,

I was seeking for some avatars that I can use in LiaScript as teachers for educational content ... 

Maybe this is something for you, we use easy-speech as a single interface to TTS of different browsers, which works very good for us. 

https://github.com/leaonline/easy-speech

**Comment by met4citizen** [comment]
Thanks - and thanks for the link.

I just checked out the easy-speech project. Unfortunately, it can't be used with the TalkingHead class because it doesn't provide word-to-audio timestamps, which are essential for accurate lip-sync. It is the same issue as with the free Web Speech API, which easy-speech uses internally.
