### ISSUE TITLE
Possibility for using custom audio

### ISSUE THREAD

**Issue by christo-zero-john** [met4citizen/TalkingHead#55]
Is there any way to use custom audio (For example auio in my system) instead of using google tts or others

**Comment by met4citizen** [comment]
Yes, you can use the `speakAudio` method instead of `speakText`. However, in addition to the audio, you'll need to provide the words and their timestamps for accurate lip-sync. One way to obtain these is by using some transcription service. For an example, refer to the `mp3.html` app in the examples directory.

**Comment by christo-zero-john** [comment]
> Yes, you can use the `speakAudio` method instead of `speakText`. However, in addition to the audio, you'll need to provide the words and their timestamps for accurate lip-sync. One way to obtain these is by using some transcription service. For an example, refer to the `mp3.html` app in the examples directory.

Really! Thanks for the help and this library tooo. It was a big help for my project

**Comment by christo-zero-john** [comment]
Hi So can I use it without google tts api key. I want to use a hugging face model to convert text to speech and animate the face accordingly. How should I do that

**Comment by christo-zero-john** [comment]
Okay. Thanks for the help.
