### ISSUE TITLE
can i use msedge tts for lip sync?

### ISSUE THREAD

**Issue by 24wemy** [met4citizen/TalkingHead#64]

**Comment by met4citizen** [comment]
I'm not sure. In addition to audio, the TalkingHead class requires word-level timestamps for accurate lip-sync and the MSEdge TTS appears to be a very limited version of Microsoft Azure TTS. However, it does include a `wordBoundaryEnabled` option in its request headers. If setting that flag to `true` works, and the server actually delivers word-level timestamps, then you might be able to make it work.

**Comment by 24wemy** [comment]
I'm looking for a free TTS, because I don't have access to Google TTS or Microsoft Azure, can you help me?

**Comment by met4citizen** [comment]
The TTS you suggested doesn't seem to have any official API documentation, which implies that it is intended for Microsoft's internal use only. Moreover, the projects that use it do so by pretending to be Edge browsers, which most likely violates Microsoft's API policies. -- If you can find some legal document stating that their API can be used by anyone for free, I'm happy to help. Otherwise, no.

**Comment by met4citizen** [comment]
FYI: Last week, I was contacted by the guys at [www.nemesyslabs.com](https://www.nemesyslabs.com/) and they were kind enough to make us an API endpoint that provides word-level timestamps. The service is brand new and under construction, but if you're still interested in a free TTS with timestamps, take a look. I made a quick code example on how to use the TalkingHead class with their API: [[Source code]](https://github.com/met4citizen/TalkingHead/blob/main/examples/nemesyslabs.html) [[Test it]](https://met4citizen.github.io/TalkingHead/examples/nemesyslabs.html)
