### ISSUE TITLE
regarding lip syncing

### ISSUE THREAD

**Issue by Poornasri2003** [met4citizen/TalkingHead#65]
I am developing a mock interview evaluator. For that I need a interface with talking movenents for asking questions to make realtime scenario..How can I make use of your project here

**Comment by met4citizen** [comment]
You can start by downloading the [minimal.html](https://github.com/met4citizen/TalkingHead/blob/main/examples/minimal.html) example app. It uses Google Cloud TTS, so the only thing you need is a Google TTS API key. The example app does nothing more than load an avatar and speaks the text you provide, but once that works, you can go through the README instructions again and start adding more details, such as your own avatar, lighting, etc.

If you already know that you need to support multiple languages, you might want to skip Google TTS and use Microsoft Azure TTS instead, as it can provide viseme information for more languages. In that case, you will need to implement your own speak function in your app. If you've done JavaScript projects, this should not be too difficult, and you can find an example implementation in the TalkingHead test app (`index.html` file, `microsoftSpeak` and `microsoftProcessQueue` functions).

I'm not an expert in mock interview systems, but I assume it would be good to make the environment as realistic as possible. If so, you might be looking for a more realistic 3D avatar instead of the cartoonish Ready Player Me models. In that case, read the related discussion in issue #44

I'm sure there are many more details to consider, but my suggestion is to experiment a bit first to see if the TalkingHead class fits your needs.

**Comment by met4citizen** [comment]
I will close this issue, but feel free to reply if you have further questions.
