### ISSUE TITLE
how to add my own tts

### ISSUE THREAD

**Issue by chang998** [met4citizen/TalkingHead#9]
hello, sorry for bothering.... again.
but i discovered that the app when it takes the response from the openapi/my api
___________________________________________
response : 

data: {"id": "chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK", "object": "chat.completion.chunk", "created": 1709363880, "model": "gpt-3.5-turbo-0125", "system_fingerprint": "fp_2b778c6b35", "choices": [{"index": 0, "delta": {"content": "How are you doing?"}, "logprobs": null, "finish_reason": null}]}

data: {"id": "chatcmpl-8yDv6isoXkNtoFc45N1uPAUlhrQSK", "object": "chat.completion.chunk", "created": 1709363880, "model": "gpt-3.5-turbo-0125", "system_fingerprint": "fp_2b778c6b35", "choices": [{"index": 0, "delta": {"content": "Im doing fine!"}, "logprobs": null, "finish_reason": null}]}

data: [DONE]
___________________________________________________
it sends it to the gtts without displaying the response 
so i started making my python api gtts server  (with gemini ai bec ive never used gtts so i dont know much in it)
im gonna give you the python code explained by chatgpt (gtts part only for not being too long ) and the response:
_____________________________________________________________________________
python explained : 

Certainly! Let's break down the code part by part:

1. **Function Definition and Route Decorator:**
    ```python
    @app.route('/gtts', methods=['POST'])
    def text_to_speech():
    ```
    - This part defines a function named `text_to_speech()` that will handle POST requests to the `/gtts` endpoint.

2. **Try-Except Block:**
    ```python
    try:
    ```
    - This line starts a `try` block, indicating that the code inside it will be executed, and exceptions will be caught and handled if they occur.

3. **Parsing JSON Request Data:**
    ```python
    data = request.json
    ```
    - This line extracts the JSON data from the request body and parses it into a Python dictionary named `data`.

4. **Extracting SSML and Language Code:**
    ```python
    ssml = data['input']['ssml']
    language_code = 'en-US'
    ```
    - These lines extract the SSML content from the parsed JSON data and set the language code to 'en-US' as a default value.

5. **Extracting Audio Configuration Parameters:**
    ```python
    audio_encoding = data['audioConfig']['audioEncoding']
    speaking_rate = data['audioConfig']['speakingRate']
    pitch = data['audioConfig']['pitch']
    volume_gain_db = data['audioConfig']['volumeGainDb']
    ```
    - These lines extract various audio configuration parameters from the JSON data received in the request.

6. **Creating gTTS Object:**
    ```python
    tts = gTTS(text=ssml, lang=language_code, slow=speaking_rate < 1.0)
    ```
    - This line creates a gTTS (Google Text-to-Speech) object with the specified SSML text, language code, and optionally sets the speed of speech based on the `speaking_rate` parameter.

7. **Creating BytesIO Object:**
    ```python
    output = io.BytesIO()
    ```
    - This line creates a BytesIO object, which is an in-memory binary stream used to store the audio data generated by gTTS.

8. **Writing Audio to BytesIO Object:**
    ```python
    tts.write_to_fp(output)
    ```
    - This line writes the audio generated by gTTS to the BytesIO stream.

9. **Encoding Audio Data as Base64:**
    ```python
    encoded_audio = base64.b64encode(output.getvalue()).decode('utf-8')
    ```
    - This line encodes the audio data stored in the BytesIO stream as Base64 format and converts it to a UTF-8 encoded string. This prepares the audio data for embedding in JSON.

10. **Constructing Response Dictionary:**
    ```python
    response = {
        "name": "generated_audio",
        "audioContent": encoded_audio
    }
    ```
    - This part constructs a response dictionary containing the name of the audio content and the Base64-encoded audio data.

11. **Returning JSON Response:**
    ```python
    return jsonify(response)
    ```
    - Finally, the function returns the JSON representation of the response dictionary to the client. This sends the audio content back as a JSON response.

This breakdown explains how each part of the code contributes to processing the POST request to generate text-to-speech audio content using gTTS and returning it as a JSON response.
_________________________________________________________________________
Response: 

{
    "audioContent": "//NExAAAAANIAUAAAP9ga126Gozf8YaeaYEYIF/9927HbWP853ZnDg/toooo long random characters.......",
    "name": "generated_audio"
}
___________________________________________________________________________________________________________________________________________
and i get... nothing i even tried this in minimal.html BUT ive found this in the console : 
Error: TypeError: Cannot read properties of undefined (reading 'forEach')
    at TalkingHead.startSpeaking (talkinghead.mjs:2370:29)
but i (THINK) not very sure that the error is from the talkinghead.mjs which is the old version. i think that you made an update to it a day ago if not pls correct me and pls tell me which is the expected response from gtts to make one like it

**Comment by met4citizen** [comment]
In order to synchronize the audio, lip movement and the subtitles (text output), the class needs - in addition to the original text - the audio and word timestamps. For this, by default, the class uses Google TTS service.

The `minimal.html` example code illustrates how you can just give the class the Google TTS endpoint in `ttsEndpoint` and your own API key in `ttsApikey`. The `index.html`, however, uses another approach in which the client-side code doesn't have to know your private API key. Instead of calling the Google TTS directly, the class calls a proxy (in this case the `/gtts/` URL)  with the temporary JWT token. If the JWT token is not expired and it has a valid signature, the server-side proxy is supposed to add the API key to the request and pass it as such to the Google TTS service.

You see an error because your response is not a valid Google TTS response. The class expects to see a `v1beta1` response with `enableTimePointing` enabled. That is, the JSON response must not only provide the audio but also the time point information for the SSML mark tags. These timepoints are needed for accurate lip-sync. (This is also the main reason why the class uses a paid TTS service instead of the free Web Speech API)

Here is an example of a valid response:

```javascript
{
    "audioContent": "//NExAAScII0AHmSSB0gLZxIx/HgKx...<full string not shown>",
    "timepoints": [
        {
            "markName": "1",
            "timeSeconds": 0.3149999976158142
        },
        {
            "markName": "2",
            "timeSeconds": 0.4399999976158142
        }
    ],
    "audioConfig": {
        "audioEncoding": "MP3",
        "speakingRate": 1,
        "pitch": 0,
        "volumeGainDb": 0,
        "sampleRateHertz": 24000,
        "effectsProfileId": []
    }
}
```

Mark names must match the original SSML mark names. You can refer to Google TTS documentation for more information about the `v1beta1` REST API:

https://cloud.google.com/text-to-speech/docs/reference/rest/v1beta1/text/synthesize
